version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "your-username"  # Replace with your GitHub username
    assignees:
      - "your-username"  # Replace with your GitHub username